/**
 * Service worker — the offline guarantee, and the freshness guarantee.
 *
 * Every file the app needs is precached on install, so once the page has been
 * opened one time it works with the radio off: no module fetch, no font, no
 * icon ever needs the network again. Games live in localStorage and never
 * touch it in the first place.
 *
 * Freshness is the harder half. GitHub Pages serves every asset from an
 * unversioned URL with a short max-age, which gives two ways to serve a stale
 * file, and both are closed here:
 *
 *   - `cache.addAll` reads through the browser's HTTP cache, so a newly named
 *     cache could be filled with the *previous* release's bytes. Every
 *     precache fetch therefore uses `cache: 'reload'`.
 *   - A worker never re-fetches a URL it has already cached, so a changed file
 *     behind an unchanged URL would live forever. PRECACHE keys each entry by
 *     a content hash, so changing a byte changes the key.
 *
 * Between them, a user never has to hard refresh to be running the current
 * build. PRECACHE is generated by tools/build-sw.mjs and checked in CI.
 */

/* @generated-precache-start */
// Generated by tools/build-sw.mjs — do not edit by hand.
// Each entry is [url, content hash]; the hash becomes the cache key, so a
// changed file is always a cache miss and can never be served stale.
const PRECACHE = [
  ['./', 'b2330e288c'],
  ['./index.html', 'b2330e288c'],
  ['./manifest.webmanifest', '629cdd3b3d'],
  ['./styles/app.css', '88ec6b65ca'],
  ['./src/chart.js', '76ae482414'],
  ['./src/dom.js', '8b40d7743d'],
  ['./src/export.js', 'a400388b43'],
  ['./src/i18n.js', 'afc8f64e78'],
  ['./src/locales/de.js', '7f01412093'],
  ['./src/locales/en.js', '1fecddb612'],
  ['./src/locales/es.js', '99a78ea1d7'],
  ['./src/locales/fr.js', '25795cb08f'],
  ['./src/locales/it.js', '09901fc665'],
  ['./src/locales/pt.js', '52a9ec227d'],
  ['./src/main.js', '222e549efa'],
  ['./src/model.js', '904c0640e3'],
  ['./src/roster.js', '3a0ef0dd42'],
  ['./src/share.js', 'e762331893'],
  ['./src/sheet.js', 'ce663405cb'],
  ['./src/sortable.js', '3164736804'],
  ['./src/storage.js', 'f50ab9834d'],
  ['./src/store.js', 'b237187e06'],
  ['./src/suggest.js', 'daaf6df27c'],
  ['./src/ui.js', '5c37543b74'],
  ['./src/version.js', '61ac537907'],
  ['./src/views/board.js', '03b663a497'],
  ['./src/views/chart.js', '7b2f5d5336'],
  ['./src/views/games.js', '176de9b4a3'],
  ['./src/views/play.js', 'c8477f1540'],
  ['./src/views/roundsheet.js', '7e7f1c81d0'],
  ['./src/views/settings.js', 'b651ca0318'],
  ['./src/views/setup.js', '7eee5284c3'],
  ['./src/views/share.js', '0be0d92de1'],
  ['./src/views/stairs.js', '837049aef2'],
  ['./assets/fonts/fraunces-latin-ext.woff2', 'a2930b27d1'],
  ['./assets/fonts/fraunces-latin.woff2', '7234ed860a'],
  ['./assets/fonts/instrument-sans-latin-ext.woff2', 'c4fcfea41f'],
  ['./assets/fonts/instrument-sans-latin.woff2', '2ee17598a9'],
  ['./assets/icons/apple-touch-icon.png', 'ee392b9766'],
  ['./assets/icons/favicon.svg', '92e42f5c0c'],
  ['./assets/icons/icon-192.png', '6d76e5a0fc'],
  ['./assets/icons/icon-512.png', '104e01baf0'],
  ['./assets/icons/maskable-512.png', 'a9f6fd629c'],
];
/* @generated-precache-end */

/** Rebuilt whenever any precached file changes, since the hashes live here. */
const CACHE = 'escalier-precache';

/** The cache key for an asset: its URL plus its content hash. */
function keyFor(url, rev) {
  return `${url}?v=${rev}`;
}

/** Assets whose absence must not cost the user offline support. */
const OPTIONAL = /\/assets\//;

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE);
      const wanted = new Set(PRECACHE.map(([url, rev]) => new URL(keyFor(url, rev), self.location).href));

      // Only fetch what is actually new: an unchanged file keeps its entry
      // across releases, so an update costs one request per changed file.
      const existing = new Set((await cache.keys()).map((request) => request.url));

      const required = [];
      const optional = [];
      for (const [url, rev] of PRECACHE) {
        const href = new URL(keyFor(url, rev), self.location).href;
        if (existing.has(href)) continue;
        (OPTIONAL.test(url) ? optional : required).push(keyFor(url, rev));
      }

      // `reload` bypasses the HTTP cache, so a short max-age cannot hand us
      // the previous release's body under the new hash.
      await Promise.all(
        required.map(async (target) => {
          const response = await fetch(new Request(target, { cache: 'reload' }));
          if (!response.ok) throw new Error(`precache failed: ${target} (${response.status})`);
          await cache.put(target, response);
        })
      );
      await Promise.allSettled(
        optional.map(async (target) => {
          const response = await fetch(new Request(target, { cache: 'reload' }));
          if (response.ok) await cache.put(target, response);
        })
      );

      // Superseded entries are NOT removed here. Installing happens while the
      // previous worker is still serving pages, and it still needs its own
      // (now superseded) entries — deleting them during install would break
      // the running app for any user who is offline between install and
      // activate. Cleanup belongs in activate, once nothing is using them.
    })()
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      // Caches from the older, version-named scheme.
      const keys = await caches.keys();
      await Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key)));

      // Now that the previous worker has stopped, drop the entries it was
      // using for files that have since changed or gone away.
      const cache = await caches.open(CACHE);
      const wanted = new Set(PRECACHE.map(([url, rev]) => new URL(keyFor(url, rev), self.location).href));
      await Promise.all(
        (await cache.keys()).map(async (request) => {
          if (!wanted.has(request.url)) await cache.delete(request);
        })
      );

      await self.clients.claim();
    })()
  );
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

/** Look an incoming request up against the hashed precache. */
async function matchPrecached(cache, pathname) {
  const scopePath = new URL('./', self.location).pathname;
  const relative = pathname.startsWith(scopePath) ? `./${pathname.slice(scopePath.length)}` : pathname;
  const entry = PRECACHE.find(([url]) => url === relative || (relative === './' && url === './'));
  if (!entry) return null;
  return cache.match(keyFor(entry[0], entry[1]));
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Navigations resolve to the app shell: routing is client-side and the
  // fragment (where shared games travel) never reaches the network.
  if (request.mode === 'navigate') {
    event.respondWith(
      (async () => {
        const root = new URL('./', self.location);

        // Serving the shell for a deeper path would leave its relative module
        // URLs resolving against that path, so the page would load and never
        // boot. Send the browser to the root instead — it carries the fragment
        // across, so a shared game still arrives.
        if (url.pathname !== root.pathname && url.pathname !== `${root.pathname}index.html`) {
          return Response.redirect(`${root.href}${url.search}`, 302);
        }

        const cache = await caches.open(CACHE);
        const shell = await matchPrecached(cache, new URL('./index.html', self.location).pathname);
        if (shell) return shell;
        try {
          return await fetch(request);
        } catch {
          return new Response('<h1>Offline</h1>', { status: 503, headers: { 'Content-Type': 'text/html' } });
        }
      })()
    );
    return;
  }

  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE);
      const cached = await matchPrecached(cache, url.pathname);
      if (cached) return cached;

      // Not one of ours: go to the network, and do not grow the cache with it.
      return fetch(request);
    })()
  );
});
