/**
 * Stamp the service worker's precache list with content hashes.
 *
 * GitHub Pages serves every asset from an unversioned URL with a short
 * max-age, which leaves two ways to hand a user a stale file:
 *
 *   1. `cache.addAll` reads through the browser's HTTP cache, so a freshly
 *      named cache can be filled with the previous release's bytes. `sw.js`
 *      defeats that with `cache: 'reload'`.
 *   2. The worker only fetches a URL it has never cached. If a file changes
 *      but its URL does not, an already-populated cache keeps the old body
 *      forever.
 *
 * Hashing the content into the cache key closes the second one: change a byte
 * and the URL changes, so the entry is genuinely new. Because the hashes live
 * inside `sw.js`, any content change also changes the worker itself, which is
 * what makes the browser install a new one. Nobody ever has to hard refresh.
 *
 *   node tools/build-sw.mjs          rewrite sw.js in place
 *   node tools/build-sw.mjs --check  exit 1 if it is out of date
 */

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SW = join(ROOT, 'sw.js');

const START = '/* @generated-precache-start */';
const END = '/* @generated-precache-end */';

/** Everything the app needs to run with the radio off. */
function collect() {
  const shell = ['index.html', 'manifest.webmanifest', 'styles/app.css'];
  const code = walk('src').filter((p) => p.endsWith('.js'));
  const assets = walk('assets').filter((p) => !p.endsWith('.txt'));
  return [...shell, ...code.sort(), ...assets.sort()];
}

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(join(ROOT, dir), { withFileTypes: true })) {
    const rel = `${dir}/${entry.name}`;
    if (entry.isDirectory()) out.push(...walk(rel));
    else out.push(rel);
  }
  return out;
}

/** Text files whose line endings differ between a checkout and a working tree. */
const TEXT = /\.(js|mjs|css|html|json|webmanifest|svg|txt)$/i;

/**
 * Content hash, normalised so it does not depend on the platform.
 *
 * `.gitattributes` stores text with LF, but a Windows working tree may hold
 * CRLF. Hashing raw bytes would then produce one value locally and a different
 * one in CI, and the manifest check would fail on a commit that is perfectly
 * correct. The hash is only a cache key — it never has to match the bytes on
 * the wire — so normalising line endings first is safe and makes it stable.
 */
function hash(relPath) {
  const bytes = readFileSync(join(ROOT, relPath));
  const content = TEXT.test(relPath) ? bytes.toString('utf8').replace(/\r\n/g, '\n') : bytes;
  return createHash('sha256').update(content).digest('hex').slice(0, 10);
}

function build() {
  const files = collect();
  const lines = files.map((file) => `  ['./${file}', '${hash(file)}'],`);

  // The bare start URL shares index.html's hash: it is the same document, and
  // it must be revalidated whenever the shell changes.
  const indexHash = hash('index.html');
  lines.unshift(`  ['./', '${indexHash}'],`);

  return [
    START,
    '// Generated by tools/build-sw.mjs — do not edit by hand.',
    '// Each entry is [url, content hash]; the hash becomes the cache key, so a',
    '// changed file is always a cache miss and can never be served stale.',
    'const PRECACHE = [',
    ...lines,
    '];',
    END,
  ].join('\n');
}

function rewrite(source, block) {
  const from = source.indexOf(START);
  const to = source.indexOf(END);
  if (from < 0 || to < 0) throw new Error('sw.js is missing its generated precache markers');
  return source.slice(0, from) + block + source.slice(to + END.length);
}

const source = readFileSync(SW, 'utf8');
const next = rewrite(source, build());
const check = process.argv.includes('--check');

if (next === source) {
  process.stdout.write('sw.js precache is up to date\n');
} else if (check) {
  process.stderr.write('sw.js precache is stale — run `npm run build:sw` and commit the result\n');
  process.exit(1);
} else {
  writeFileSync(SW, next);
  const count = next.slice(next.indexOf(START), next.indexOf(END)).split('\n').filter((l) => l.startsWith("  ['")).length;
  process.stdout.write(`sw.js precache rewritten: ${count} entries\n`);
}

// Ignore a mtime-only touch: statSync keeps this honest if anyone wonders.
void statSync;
